In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import SGDClassifier, LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import *
from sklearn.datasets import load_digits


In [2]:
digit = load_digits()

In [3]:
print(dir(digit))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [4]:
data = digit.data
label = digit.target

In [5]:
print(data)

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  1. ...  6.  0.  0.]
 [ 0.  0.  2. ... 12.  0.  0.]
 [ 0.  0. 10. ... 12.  1.  0.]]


In [6]:
print(label)

[0 1 2 ... 8 9 8]


In [7]:
print(digit.target_names)

[0 1 2 3 4 5 6 7 8 9]


In [10]:
print(digit.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

In [11]:
X_train, X_test, y_train, y_test = train_test_split(data, label, test_size = 0.2, stratify = label, random_state = 0)

In [12]:
dt = DecisionTreeClassifier()
rf = RandomForestClassifier()
svm = SVC()
sgd = SGDClassifier()
ld = LogisticRegression()

In [13]:
dt.fit(X_train, y_train)
dt_pred = dt.predict(X_test)
print(classification_report(y_test, dt_pred))

              precision    recall  f1-score   support

           0       0.94      0.92      0.93        36
           1       0.83      0.81      0.82        36
           2       0.86      0.89      0.87        35
           3       0.88      0.78      0.83        37
           4       0.77      0.83      0.80        36
           5       0.87      0.92      0.89        37
           6       0.97      0.92      0.94        36
           7       0.86      0.89      0.88        36
           8       0.78      0.83      0.81        35
           9       0.80      0.78      0.79        36

    accuracy                           0.86       360
   macro avg       0.86      0.86      0.86       360
weighted avg       0.86      0.86      0.86       360



In [34]:
print('accuracy :', accuracy_score(y_test, dt_pred))
print('recall :', recall_score(y_test, dt_pred, average='macro'))
print('precision :',precision_score(y_test, dt_pred, average='macro'))
print('f1 score :', f1_score(y_test, dt_pred, average='macro'))

accuracy : 0.8555555555555555
recall : 0.8555877305877306
precision : 0.857159008629597
f1 score : 0.8556884002081866


In [29]:
rf.fit(X_train, y_train)
rf_pred = rf.predict(X_test)
print(classification_report(y_test, rf_pred))

              precision    recall  f1-score   support

           0       1.00      0.97      0.99        36
           1       0.92      0.97      0.95        36
           2       1.00      1.00      1.00        35
           3       0.97      0.97      0.97        37
           4       0.97      0.94      0.96        36
           5       0.93      1.00      0.96        37
           6       1.00      1.00      1.00        36
           7       0.92      1.00      0.96        36
           8       1.00      0.89      0.94        35
           9       0.97      0.92      0.94        36

    accuracy                           0.97       360
   macro avg       0.97      0.97      0.97       360
weighted avg       0.97      0.97      0.97       360



In [39]:
print('accuracy :', accuracy_score(y_test, rf_pred))
print('recall :', recall_score(y_test, rf_pred, average='macro'))
print('precision :',precision_score(y_test, rf_pred, average='macro'))
print('f1 score :', f1_score(y_test, rf_pred, average='macro'))

accuracy : 0.9666666666666667
recall : 0.9664242814242814
precision : 0.9684119334351534
f1 score : 0.9665870934039947


In [41]:
svm.fit(X_train, y_train)
svm_pred = svm.predict(X_test)
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.95      1.00      0.97        36
           2       1.00      1.00      1.00        35
           3       1.00      0.97      0.99        37
           4       1.00      0.94      0.97        36
           5       0.97      1.00      0.99        37
           6       1.00      1.00      1.00        36
           7       0.97      1.00      0.99        36
           8       0.94      0.94      0.94        35
           9       1.00      0.97      0.99        36

    accuracy                           0.98       360
   macro avg       0.98      0.98      0.98       360
weighted avg       0.98      0.98      0.98       360



In [42]:
print('accuracy :', accuracy_score(y_test, svm_pred))
print('recall :', recall_score(y_test, svm_pred, average='macro'))
print('precision :',precision_score(y_test, svm_pred, average='macro'))
print('f1 score :', f1_score(y_test, svm_pred, average='macro'))

accuracy : 0.9833333333333333
recall : 0.9832496782496781
precision : 0.9836882747409064
f1 score : 0.9832443586609128


In [43]:
sgd.fit(X_train, y_train)
sgd_pred = sgd.predict(X_test)
print(classification_report(y_test, sgd_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.83      0.97      0.90        36
           2       1.00      1.00      1.00        35
           3       1.00      0.89      0.94        37
           4       1.00      0.92      0.96        36
           5       0.97      0.97      0.97        37
           6       0.95      1.00      0.97        36
           7       0.97      0.97      0.97        36
           8       0.80      0.80      0.80        35
           9       0.97      0.94      0.96        36

    accuracy                           0.95       360
   macro avg       0.95      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



In [44]:
print('accuracy :', accuracy_score(y_test, sgd_pred))
print('recall :', recall_score(y_test, sgd_pred, average='macro'))
print('precision :',precision_score(y_test, sgd_pred, average='macro'))
print('f1 score :', f1_score(y_test, sgd_pred, average='macro'))

accuracy : 0.9472222222222222
recall : 0.9470420420420421
precision : 0.9497325521009733
f1 score : 0.9472729426464884


In [45]:
ld.fit(X_train, y_train)
ld_pred = ld.predict(X_test)
print(classification_report(y_test, ld_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        36
           1       0.85      0.97      0.91        36
           2       1.00      0.97      0.99        35
           3       0.97      1.00      0.99        37
           4       1.00      0.94      0.97        36
           5       0.97      0.95      0.96        37
           6       0.97      0.97      0.97        36
           7       0.97      0.97      0.97        36
           8       0.94      0.86      0.90        35
           9       0.95      0.97      0.96        36

    accuracy                           0.96       360
   macro avg       0.96      0.96      0.96       360
weighted avg       0.96      0.96      0.96       360



C:\Users\dlarh\anaconda3\envs\adp\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [46]:
print('accuracy :', accuracy_score(y_test, ld_pred))
print('recall :', recall_score(y_test, ld_pred, average='macro'))
print('precision :',precision_score(y_test, ld_pred, average='macro'))
print('f1 score :', f1_score(y_test, ld_pred, average='macro'))

accuracy : 0.9611111111111111
recall : 0.9607850707850707
precision : 0.9627455359724294
f1 score : 0.9610468445245186


성능은 Support Vector Machine이 가장 좋게 나온다.

digits 데이터셋은 데이터가 균등하고 비교적 구분이 쉬운 데이터라 accuracy, precision, recall, f1score 네 지표의 값이 모두 비슷하다. 균등한 데이터이기 때문에 4개중 어느것을 지표로 선택해도 문제가 없을 것이다.